### PR TITLE
Refs #6318 Annotations name collision only must be performed against … [6324]

### LINKED ISSUE #34: Illegal identifier: ... is already defined (Annotation: ...) [6318]
Using Fast-RTPS latest upstream master. FastRTPSGen 1.9.0.

Trying to parse the following IDL file:
```
#ifndef __trajectory_waypoint__idl__
#define __trajectory_waypoint__idl__

typedef float trajectory_waypoint__float_array_3[3];

struct trajectory_waypoint
{
    unsigned long long timestamp;
    trajectory_waypoint__float_array_3 position;
    trajectory_waypoint__float_array_3 velocity;
    trajectory_waypoint__float_array_3 acceleration;
    float yaw;
    float yaw_speed;
    boolean point_valid;
    octet type;

}; // struct trajectory_waypoint

#pragma keylist trajectory_waypoint

#endif  // __trajectory_waypoint__idl__
```

Results in the following error:
```sh
/home/nuno/PX4/Firmware/build/px4_sitl_rtps/src/modules/micrortps_bridge/micrortps_client/micrortps_agent/idl/trajectory_waypoint.idl:12:47: error: Illegal identifier: position is already defined (Annotation: position)
```

@LuisGP can you provide a pointer on why is it happening? Also this same IDL is include on another IDL that depends on this (nested type).

Note that this IDL was being parsed alright on version 1.9.0.

Thanks in advance for your help!

### PR DESCRIPTION
**Pull request by LuisGP**
…other annotations.

Fixes #34

### CODE REVIEW

**Comment by TSC21** [comment]
@LuisGP is this supposed to address https://github.com/eProsima/IDL-Parser/issues/34?

**Comment by LuisGP** [comment]
> @LuisGP is this supposed to address #34?

Exactly.

**Comment by TSC21** [comment]
> > @LuisGP is this supposed to address #34?
> 
> Exactly.

Great!

**Comment by TSC21** [comment]
@LuisGP @laura-eprosima can this be brought in and be added to the 1.9.1 release?

**Pull request merged**
